export const SUPPORTED_NETWORKS = {
  evm: [
    {
      chain: "Ethereum",
      mainnet: "eth-mainnet",
      testnets: ["eth-sepolia", "eth-holesky", "eth-hoodi"],
    },
    { chain: "Arbitrum", mainnet: "arb-mainnet", testnets: ["arb-sepolia"] },
    { chain: "Arbitrum Nova", mainnet: "arbnova-mainnet", testnets: [] },
    { chain: "Base", mainnet: "base-mainnet", testnets: ["base-sepolia"] },
    { chain: "BNB Chain", mainnet: "bnb-mainnet", testnets: ["bnb-testnet"] },
    { chain: "Avalanche", mainnet: "avax-mainnet", testnets: [] },
    { chain: "Polygon", mainnet: "polygon-mainnet", testnets: [] },
    { chain: "Polygon zkEVM", mainnet: "polygonzkevm-mainnet", testnets: [] },
    { chain: "Optimism", mainnet: "opt-mainnet", testnets: ["opt-sepolia"] },
    {
      chain: "zkSync",
      mainnet: "zksync-mainnet",
      testnets: ["zksync-sepolia"],
    },
    { chain: "Linea", mainnet: "linea-mainnet", testnets: ["linea-sepolia"] },
    {
      chain: "Scroll",
      mainnet: "scroll-mainnet",
      testnets: ["scroll-sepolia"],
    },
    { chain: "Blast", mainnet: "blast-mainnet", testnets: ["blast-sepolia"] },
    { chain: "Gnosis", mainnet: "gnosis-mainnet", testnets: [] },
    { chain: "Metis", mainnet: "metis-mainnet", testnets: [] },
    { chain: "Celo", mainnet: "celo-mainnet", testnets: ["celo-sepolia"] },
    {
      chain: "Mantle",
      mainnet: "mantle-mainnet",
      testnets: ["mantle-sepolia"],
    },
    { chain: "Mode", mainnet: "mode-mainnet", testnets: ["mode-sepolia"] },
    { chain: "Moonbeam", mainnet: "moonbeam-mainnet", testnets: [] },
    { chain: "Astar", mainnet: "astar-mainnet", testnets: [] },
    { chain: "Ronin", mainnet: "ronin-mainnet", testnets: [] },
    {
      chain: "Rootstock",
      mainnet: "rootstock-mainnet",
      testnets: ["rootstock-testnet"],
    },
    { chain: "Frax", mainnet: "frax-mainnet", testnets: ["frax-hoodi"] },
    { chain: "Sei", mainnet: "sei-mainnet", testnets: ["sei-testnet"] },
    { chain: "Sonic", mainnet: "sonic-mainnet", testnets: ["sonic-testnet"] },
    { chain: "Zora", mainnet: "zora-mainnet", testnets: ["zora-sepolia"] },
    { chain: "Shape", mainnet: "shape-mainnet", testnets: ["shape-sepolia"] },
    { chain: "Soneium", mainnet: "soneium-mainnet", testnets: [] },
    { chain: "Ink", mainnet: "ink-mainnet", testnets: ["ink-sepolia"] },
    {
      chain: "Unichain",
      mainnet: "unichain-mainnet",
      testnets: ["unichain-sepolia"],
    },
    { chain: "ApeChain", mainnet: "apechain-mainnet", testnets: [] },
    { chain: "Lens", mainnet: "lens-mainnet", testnets: ["lens-sepolia"] },
    {
      chain: "ZetaChain",
      mainnet: "zetachain-mainnet",
      testnets: ["zetachain-testnet"],
    },
    {
      chain: "WorldChain",
      mainnet: "worldchain-mainnet",
      testnets: ["worldchain-sepolia"],
    },
    {
      chain: "StarkNet",
      mainnet: "starknet-mainnet",
      testnets: ["starknet-sepolia"],
    },
    {
      chain: "Hyperliquid",
      mainnet: "hyperliquid-mainnet",
      testnets: ["hyperliquid-testnet"],
    },
    { chain: "Bob", mainnet: "bob-mainnet", testnets: ["bob-sepolia"] },
    { chain: "Boba", mainnet: "boba-mainnet", testnets: ["boba-sepolia"] },
    { chain: "Degen", mainnet: "degen-mainnet", testnets: ["degen-sepolia"] },
    { chain: "Flow", mainnet: "flow-mainnet", testnets: ["flow-testnet"] },
    { chain: "opBNB", mainnet: "opbnb-mainnet", testnets: ["opbnb-testnet"] },
    {
      chain: "CrossFi",
      mainnet: "crossfi-mainnet",
      testnets: ["crossfi-testnet"],
    },
    { chain: "Mythos", mainnet: "mythos-mainnet", testnets: [] },
    { chain: "Race", mainnet: "race-mainnet", testnets: ["race-sepolia"] },
    {
      chain: "Polynomial",
      mainnet: "polynomial-mainnet",
      testnets: ["polynomial-sepolia"],
    },
    { chain: "Story", mainnet: "story-mainnet", testnets: [] },
    {
      chain: "Superseed",
      mainnet: "superseed-mainnet",
      testnets: ["superseed-sepolia"],
    },
    {
      chain: "Abstract",
      mainnet: "abstract-mainnet",
      testnets: ["abstract-testnet"],
    },
    { chain: "Anime", mainnet: "anime-mainnet", testnets: ["anime-sepolia"] },
    { chain: "Berachain", mainnet: "berachain-mainnet", testnets: [] },
    {
      chain: "MegaETH",
      mainnet: "megaeth-mainnet",
      testnets: ["megaeth-testnet"],
    },
    { chain: "Monad", mainnet: "monad-mainnet", testnets: ["monad-testnet"] },
    {
      chain: "Humanity",
      mainnet: "humanity-mainnet",
      testnets: ["humanity-testnet"],
    },
    {
      chain: "Botanix",
      mainnet: "botanix-mainnet",
      testnets: ["botanix-testnet"],
    },
    { chain: "Citrea", mainnet: "citrea-mainnet", testnets: [] },
    { chain: "Edge", mainnet: "edge-mainnet", testnets: ["edge-testnet"] },
    { chain: "EarnM", mainnet: "earnm-mainnet", testnets: ["earnm-sepolia"] },
    { chain: "Galactica", mainnet: "galactica-mainnet", testnets: [] },
    {
      chain: "Gensyn",
      mainnet: "gensyn-mainnet",
      testnets: ["gensyn-testnet"],
    },
    {
      chain: "Plasma",
      mainnet: "plasma-mainnet",
      testnets: ["plasma-testnet"],
    },
    {
      chain: "Stable",
      mainnet: "stable-mainnet",
      testnets: ["stable-testnet"],
    },
    { chain: "Standard", mainnet: "standard-mainnet", testnets: [] },
    { chain: "Settlus", mainnet: "settlus-mainnet", testnets: [] },
    { chain: "Unite", mainnet: "unite-mainnet", testnets: ["unite-testnet"] },
    {
      chain: "World Mobile",
      mainnet: "worldmobilechain-mainnet",
      testnets: ["worldmobile-testnet"],
    },
    { chain: "XMTP", mainnet: "xmtp-mainnet", testnets: [] },
    { chain: "xProtocol", mainnet: "xprotocol-mainnet", testnets: [] },
    { chain: "ADI", mainnet: "adi-mainnet", testnets: ["adi-testnet"] },
    { chain: "Alterscope", mainnet: "alterscope-mainnet", testnets: [] },
    { chain: "Clankermon", mainnet: "clankermon-mainnet", testnets: [] },
    { chain: "Commons", mainnet: "commons-mainnet", testnets: [] },
    {
      chain: "Celestia Bridge",
      mainnet: "celestiabridge-mainnet",
      testnets: [],
    },
    { chain: "Synd", mainnet: "synd-mainnet", testnets: [] },
    { chain: "Geist", mainnet: "geist-mainnet", testnets: [] },
  ],
  beacon: [
    {
      chain: "Ethereum Beacon",
      mainnet: "eth-mainnetbeacon",
      testnets: ["eth-sepoliabeacon", "eth-holeskybeacon", "eth-hoodibeacon"],
    },
  ],
  solana: [
    { chain: "Solana", mainnet: "solana-mainnet", testnets: ["solana-devnet"] },
  ],
  nonEvm: [
    {
      chain: "Bitcoin",
      mainnet: "bitcoin-mainnet",
      testnets: ["bitcoin-testnet", "bitcoin-signet"],
    },
    { chain: "Aptos", mainnet: "aptos-mainnet", testnets: ["aptos-testnet"] },
    { chain: "Sui", mainnet: "sui-mainnet", testnets: ["sui-testnet"] },
    { chain: "Tron", mainnet: "tron-mainnet", testnets: ["tron-testnet"] },
  ],
  testnetOnly: [
    { chain: "ARC", testnets: ["arc-testnet"] },
    { chain: "OpenLoot", testnets: ["openloot-sepolia"] },
    { chain: "RISA", testnets: ["risa-testnet"] },
    { chain: "RISE", testnets: ["rise-testnet"] },
    { chain: "Tea", testnets: ["tea-sepolia"] },
    { chain: "Tempo", testnets: ["tempo-testnet"] },
  ],
  alchemyInternal: [
    "alchemy-internal",
    "alchemy-sepolia",
    "alchemyarb-fam",
    "alchemyarb-sepolia",
  ],
} as const;
